name: Node Services CI

on:
  push:
    paths:
      - 'SmartRetailProject/supplier-api/**'
      - 'SmartRetailProject/inventory-api/**'
      - 'SmartRetailProject/product-service/**'
      - 'SmartRetailProject/docker-compose.yml'
  pull_request:
    paths:
      - 'SmartRetailProject/supplier-api/**'
      - 'SmartRetailProject/inventory-api/**'
      - 'SmartRetailProject/product-service/**'
      - 'SmartRetailProject/docker-compose.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVICE_BUS_CONNECTION_STRING: ${{ secrets.SERVICE_BUS_CONNECTION_STRING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # supplier-api
      - name: Install deps (supplier-api)
        run: npm ci --prefix SmartRetailProject/supplier-api

      - name: Test (supplier-api)
        run: npm test --prefix SmartRetailProject/supplier-api || echo "no tests"

      # inventory-api
      - name: Install deps (inventory-api)
        run: npm ci --prefix SmartRetailProject/inventory-api

      - name: Test (inventory-api)
        run: npm test --prefix SmartRetailProject/inventory-api || echo "no tests"

      # product-service
      - name: Install deps (product-service)
        run: npm ci --prefix SmartRetailProject/product-service

      - name: Test (product-service)
        run: npm test --prefix SmartRetailProject/product-service || echo "no tests"
